### ISSUE TITLE
add archive.html for previous presentations

### ISSUE THREAD

**Issue by mozfreddyb** [berlinsec/berlinsec.github.io#6]
I think it's nice to credit presentations, given how much time usually invest.

also helps giving berlinsec credibility ;)

**Comment by hannob** [comment]
Did that now, feel free to enrich it with links to slides or further infos.

I only went back to our 2019 meetups, not our older ones (feel free to do, but it felt too much work to do manually and not sure how to easily script it). Also included the BerlinCrypto one.
